name: Final Assignment
on: push
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
        
      - name: build
        run: |
          chmod +x gradlew
          ./gradlew build
          ls -ltr
          
      - name: SonarCloud Analysis
        run: |
          echo "Sonar Step Executing"
          ./gradlew build sonar -Dsonar.token=${{ secrets.TOKEN_SONARCLOUD }}

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Change access permissions to file
        run: |
          chmod 777 ./build/libs/testing-web-0.0.1-SNAPSHOT.jar
          ls -lt     

      - name: Docker Build
        run: |
          docker build --tag guisoacelga75/microservicio-java:latest .
          docker images
          
      - name: Docker Push
        run: |
          docker push guisoacelga75/microservicio-java

  deploy: 
      runs-on: self-hosted
      needs: build
      steps: 
        - name: Check out repository code
          uses: actions/checkout@v4
          
