name: Final Assignment
on: push
jobs: 
  checkout: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          chmod +x gradlew
          ./gradlew build
        
    

